name: Kind

# Any change in triggers needs to be reflected in the concurrency group.
on:
  pull_request: {}
  schedule:
    - cron:  '30 */6 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || 'scheduled' }}
  cancel-in-progress: true

env:
  KIND_VERSION: v0.14.0
  KIND_CONFIG: .github/kind-config.yaml
  TIMEOUT: 2m
  LOG_TIME: 30m
  cilium_version: v1.13.1
  kubectl_version: v1.23.6

jobs:
  installation-and-connectivity:
    runs-on: ubuntu-22.04
    timeout-minutes: 40
    strategy:
      matrix:
        mode: ["classic", "helm"]
    steps:
      - name: Set mode
        run: |
          echo "CILIUM_CLI_MODE=${{ matrix.mode }}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Install kubectl
        run: |
          curl -sLO "https://dl.k8s.io/release/${{ env.kubectl_version }}/bin/linux/amd64/kubectl"
          curl -sLO "https://dl.k8s.io/${{ env.kubectl_version }}/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
        with:
          go-version: 1.20.2

      - name: Set up Go for root
        run: |
          sudo ln -sf `which go` `sudo which go` || true
          sudo go version

      - name: Build and install cilium CLI binary
        run: sudo make install

      - name: Create kind cluster
        uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00
        with:
          version: ${{ env.KIND_VERSION }}
          config: ${{ env.KIND_CONFIG }}

      # Install Cilium with HostPort support for extended connectivity test.
      - name: Install Cilium
        run: |
          cilium install \
            --version=${{ env.cilium_version }} \
            --wait=false \
            --helm-set bpf.monitorAggregation=none \
            --helm-set cni.chainingMode=portmap \
            --helm-set loadBalancer.l7.backend=envoy \
            --helm-set tls.secretsBackend=k8s

      - name: Enable Relay
        run: |
          cilium hubble enable --ui
          cilium status --wait

      - name: Relay Port Forward
        run: |
          cilium hubble port-forward&
          sleep 10s
          [[ $(pgrep -f "cilium.*hubble.*port-forward|kubectl.*port-forward.*hubble-relay" | wc -l) == 2 ]]

      - name: Connectivity Test
        run: |
          # Run the connectivity test in non-default namespace (i.e. not cilium-test)
          cilium connectivity test --debug --all-flows --test-namespace test-namespace \
            --collect-sysdump-on-failure

      - name: Uninstall cilium
        run: |
          pkill -f "cilium.*hubble.*port-forward|kubectl.*port-forward.*hubble-relay"
          cilium uninstall --wait

      - name: Install Cilium with IPsec Encryption
        if: ${{ matrix.mode == 'classic' }}
        run: |
          cilium install \
          --version=${{ env.cilium_version}} \
          --encryption=ipsec \
          --helm-set kubeProxyReplacement=disabled

      - name: Install Cilium with IPsec Encryption
        if: ${{ matrix.mode == 'helm' }}
        run: |
          kubectl create -n kube-system secret generic cilium-ipsec-keys \
            --from-literal=keys="3 rfc4106(gcm(aes)) $(echo $(dd if=/dev/urandom count=20 bs=1 2> /dev/null | xxd -p -c 64)) 128"
          cilium install \
          --version=${{ env.cilium_version}} \
          --helm-set encryption.enabled=true \
          --helm-set encryption.type=ipsec \
          --helm-set kubeProxyReplacement=disabled

      - name: Enable Relay
        run: |
          cilium hubble enable
          cilium status --wait

      - name: Relay Port Forward
        run: |
          cilium hubble port-forward&
          sleep 10s
          [[ $(pgrep -f "cilium.*hubble.*port-forward|kubectl.*port-forward.*hubble-relay" | wc -l) == 2 ]]

      - name: Connectivity test
        run: |
          cilium connectivity test --debug --force-deploy --all-flows --test-namespace another-test-namespace \
            --collect-sysdump-on-failure

      - name: Cleanup
        if: ${{ always() }}
        run: |
          cilium status
          kubectl get pods --all-namespaces -o wide
          cilium sysdump --output-filename cilium-sysdump-out --hubble-flows-count 10000
        shell: bash {0} # Disable default fail-fast behaviour so that all commands run independently

      - name: Upload Artifacts
        if: ${{ !success() }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: cilium-sysdump-out.zip
          path: cilium-sysdump-out.zip
          retention-days: 5

  helm-upgrade-clustermesh:
    runs-on: ubuntu-22.04
    timeout-minutes: 40

    env:
      CILIUM_CLI_MODE: helm
      KIND_CONFIG_1: .github/kind-config-h1.yaml
      KIND_CONFIG_2: .github/kind-config-h2.yaml
      CLUSTER1: kind-c1
      CLUSTER2: kind-c2

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Install kubectl
        run: |
          curl -sLO "https://dl.k8s.io/release/${{ env.kubectl_version }}/bin/linux/amd64/kubectl"
          curl -sLO "https://dl.k8s.io/${{ env.kubectl_version }}/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
          
      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
        with:
          go-version: 1.20.2

      - name: Set up Go for root
        run: |
          sudo ln -sf `which go` `sudo which go` || true
          sudo go version

      - name: Build and install cilium CLI binary
        run: sudo make install

      - name: Create kind cluster 1
        uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00
        with:
          version: ${{ env.KIND_VERSION }}
          config: ${{ env.KIND_CONFIG_1 }}

      - name: Install Cilium on cluster 1
        run: |
          cilium install --context $CLUSTER1 \
            --version=${{ env.cilium_version }} \
            --wait=true \
            --helm-set bpf.monitorAggregation=none \
            --helm-set cni.chainingMode=portmap

      - name: Create kind cluster 2
        uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00
        with:
          version: ${{ env.KIND_VERSION }}
          config: ${{ env.KIND_CONFIG_2 }}

      - name: Install Cilium on cluster 2
        run: |
          cilium install --context $CLUSTER2 \
            --version=${{ env.cilium_version }} \
            --wait=true \
            --helm-set bpf.monitorAggregation=none \
            --helm-set cni.chainingMode=portmap

      - name: Enable ClusterMesh on cluster 1 using helm-based upgrade
        run: |
          cilium upgrade --context $CLUSTER1 \
            --wait=true \
            --helm-set clustermesh.useAPIServer=true \
            --helm-set clustermesh.apiserver.service.type=NodePort

      - name: Copy CA cert from cluster 1 to cluster 2
        run: |
          kubectl --context $CLUSTER2 delete secret -n kube-system cilium-ca && \
          kubectl --context $CLUSTER1 get secrets -n kube-system cilium-ca -oyaml \
            | kubectl --context $CLUSTER2 apply -f - && \
          kubectl --context $CLUSTER2 delete pod -l app.kubernetes.io/part-of=cilium -A

      - name: Enable ClusterMesh on cluster 2 using helm-based upgrade
        run: |
          cilium upgrade --context $CLUSTER1 \
            --wait=true \
            --helm-set clustermesh.useAPIServer=true \
            --helm-set clustermesh.apiserver.service.type=NodePort

      - name: Rename the secrets expected by the clustermesh connect command
        run: |
          kubectl get secrets --context $CLUSTER1 \
            -n kube-system clustermesh-apiserver-remote-cert \
            -oyaml \
              | sed 's/name: .*/name: clustermesh-apiserver-client-cert/' \
              | k apply --context $CLUSTER1 -f -
          kubectl get secrets --context $CLUSTER2 \
            -n kube-system clustermesh-apiserver-remote-cert \
            -oyaml \
              | sed 's/name: .*/name: clustermesh-apiserver-client-cert/' \
              | k apply --context $CLUSTER2 -f -

      - name: Connect the two clusters using clustermesh
        run: |
          cilium clustermesh connect --context $CLUSTER1 --destination-context $CLUSTER2

      - name: Run the multicluster connectivity tests
        run: |
          cilium connectivity test --context $CLUSTER1 --multi-cluster $CLUSTER2 --debug --collect-sysdump-on-failure

      - name: Cleanup
        if: ${{ always() }}
        run: |
          cilium --context $CLUSTER1 status
          kubectl --context $CLUSTER1 get pods --all-namespaces -o wide
          cilium --context $CLUSTER1 sysdump --output-filename cilium-sysdump-out-c1
          cilium --context $CLUSTER2 status
          kubectl --context $CLUSTER2 get pods --all-namespaces -o wide
          cilium --context $CLUSTER2 sysdump --output-filename cilium-sysdump-out-c2
        shell: bash {0} # Disable default fail-fast behaviour so that all commands run independently

      - name: Upload sysdump from cluster 1
        if: ${{ !success() }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: cilium-sysdump-out-c1.zip
          path: cilium-sysdump-out-c1.zip
          retention-days: 5

      - name: Upload sysdump from cluster 2
        if: ${{ !success() }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: cilium-sysdump-out-c2.zip
          path: cilium-sysdump-out-c2.zip
          retention-days: 5
